[package]
description = "Unofficial fork for RustPython"
name = "rustpython-ruff_source_file"
version = "0.16.5"
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[lib]
name = "ruff_source_file"

[dependencies]
ruff_text_size = { package = "rustpython-ruff_text_size", version = "0.16.5", path = "../ruff_text_size", default-features = false }

get-size2 = { workspace = true, optional = true }
memchr = { version = "2.7.1", default-features = false }
serde = { workspace = true, optional = true }
spin = { version = "0.10.0", default-features = false, features = ["once"] }

[dev-dependencies]

[features]
default = ["std"]
get-size = ["dep:get-size2", "ruff_text_size/get-size", "std"]
serde = ["dep:serde", "ruff_text_size/serde", "std"]
std = ["memchr/std", "ruff_text_size/std"]

[lints]
workspace = true
